# General setup
# -------------
language: python
python:
    - "2.7"
# Allows the python virtualenv to use apt-get installed packages, which
# is essential (as ROS recommends this and pip doesn't seem to contain
# all packages, or contains them with errors).
virtualenv:
    system_site_packages: true
# Allow caching of debian (apt-get) packages. This means they're cached
# on Travis, so we still have to download/install them, but it will be
# faster than going to the ubuntu repositories.
cache: apt
services: mongodb
# Before anything, see if we can get the mongoDB troubles out of the way.
# Note that this is a Travis-CI specific problem; this is not needed in
# general.
before_install: # Use this to prepare the system to install prerequisites or dependencies
    # Define some config vars
    - export ROS_DISTRO=hydro
    # Settings to make installing script more general.
    - export ROS_CI_DESKTOP=`lsb_release -cs`  # e.g. 'precise'
    - export ROS_MASTER_URI=http://localhost:11311

notifications:
  email: false
  slack:
    secure: "K377AMS65aZiOBUekVpZZ4+/Dt0i2gX5ODEc5KOQIkS/1iolN9vY6RQbP2el90OzOmK+mQRqqsTvP3JasFeE8d6jVj1zfE4/AIQ8BmzuI+g+norDGyty30lk3DPjg7qJMql1D2RVU8f4Hl3BjlxCmzneyplILRpR2eTfpr6fe54brSUs6sESy85/vUr5AFuuCSNMUzzR07HOvxlCADAQrkFeCfe/E344fpj77u+OyP7SIH7uPdO8x5L2TL5DRsCsha+FRk/eBHBecnuW3c7D0S4IPecTY088mQuhfC6MmHmqKvQ6Bu/H2iY8Cg38cYggT90ico5zLUAUk8SlbEEKWZEpaOKlNuTGH/QDA1IGTXR6j6KxGIz7mSsALKAK1ZyD+5QXjjLXyKsoExk15s1Kp8HeJYjNJeJNQr0d+wbCfNUfppgAZH5V5tFH9cMKglK73CZuTvRb7XhflEucoVMMp5qsWqgZWffQEt/h0Hv7lWbtdNOeoGzOwooUnlvhe93jhU9Wyeu9UU6KIk61L4/RqhM9V2DKi6MbCKLhsOAEL4vdILrIMBlT84j+alTN7ORzkKbBHcfP6xipMFaFIx/65zQ6qYs+DcXbnaQ428NRK0Kzn4V7obP1W7hqio4QrFSaW6TiB3WLnq7h2lWNUeGaJfh8TKyAm61tyYyG9KC11pY="

# Commands to install dependencies
# --------------------------------
install:
    # Install ROS
    - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -sc` main" > /etc/apt/sources.list.d/ros-latest.list'
    - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin ros-$ROS_DISTRO-ros
    - sudo pip install -U setuptools
    - sudo pip install -U catkin_tools
    - pip install coverage
    - pip install coveralls
    - source /opt/ros/$ROS_DISTRO/setup.bash
    # Setup rosdep
    - sudo rosdep init
    - rosdep update
    # Create workspace.
    - mkdir -p ~/catkin_ws/src
    - cd ..; mv mongo_msg_db ~/catkin_ws/src
    - cd ~/catkin_ws/src/mongo_msg_db
    - pip install -r requirements.txt
    - cd ~/catkin_ws/src
    - git clone https://github.com/jstnhuang/mongo_msg_db_msgs.git
    - cd ~/catkin_ws/
    - catkin init
    # Install dependencies
    - rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y

before_script:
    - sleep 15
    - mongo test --eval 'db.addUser("travis", "test");'

# Command to run tests
# --------------------
script:
    - cd ~/catkin_ws/src/mongo_msg_db
    - catkin build
    - source ~/catkin_ws/devel/setup.bash
    - nosetests --with-coverage --cover-package mongo_msg_db

after_success:
    - coveralls
